/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GermanPrepositionPanel.java
 *
 * Created on 6/01/2011, 10:08:54 AM
 */

package com.kap.view.insert;

/**
 *
 * @author Julian Caicedo (spark990@gmail.com)
 */
public class GermanPrepositionPanel extends javax.swing.JPanel {

    /** Creates new form GermanPrepositionPanel */
    public GermanPrepositionPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
