/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddCategorieDialog.java
 *
 * Created on 26/12/2010, 03:07:36 PM
 */

package com.kap.view.add;

/**
 *
 * @author Julian Caicedo (spark990@gmail.com)
 */
public class AddCategorieDialog extends javax.swing.JDialog {

    /** Creates new form AddCategorieDialog */
    public AddCategorieDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        endInitialization(parent);
    }

    private void endInitialization(java.awt.Frame parent) {
        setLocationRelativeTo(parent);
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Categorie");
        setIconImage(null);
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
